[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; If your recorded file size gets larger and runs out of SPIFFS space, 
; you might need to uncomment and define a custom partition table here:
; board_build.partitions = huge_app.csv